
/**
 * - key: viewer.viewer_definition.ViewerDefinitionAggregatedFields
 * - schema:
 * ```json
 * {
 *   "type": "string",
 *   "enum": [
 *     "",
 *     "aggregateId",
 *     "tenantId",
 *     "ownerId",
 *     "version",
 *     "eventId",
 *     "firstOperator",
 *     "operator",
 *     "firstEventTime",
 *     "eventTime",
 *     "deleted",
 *     "state",
 *     "state.availableFilters",
 *     "state.availableFilters.filters",
 *     "state.availableFilters.filters.component",
 *     "state.availableFilters.filters.field",
 *     "state.availableFilters.filters.field.format",
 *     "state.availableFilters.filters.field.label",
 *     "state.availableFilters.filters.field.name",
 *     "state.availableFilters.filters.field.type",
 *     "state.availableFilters.filters.operator",
 *     "state.availableFilters.filters.operator.defaultOperator",
 *     "state.availableFilters.filters.operator.locale",
 *     "state.availableFilters.filters.operator.supportedOperators",
 *     "state.availableFilters.filters.value",
 *     "state.availableFilters.filters.value.className",
 *     "state.availableFilters.filters.value.defaultValue",
 *     "state.availableFilters.filters.value.placeholder",
 *     "state.availableFilters.filters.value.style",
 *     "state.availableFilters.label",
 *     "state.checkable",
 *     "state.countUrl",
 *     "state.dataUrl",
 *     "state.fields",
 *     "state.fields.attributes",
 *     "state.fields.label",
 *     "state.fields.name",
 *     "state.fields.primaryKey",
 *     "state.fields.sorter",
 *     "state.fields.sorter.multiple",
 *     "state.id",
 *     "state.name"
 *   ]
 * }
 * ```
 */
export enum ViewerDefinitionAggregatedFields {
  AGGREGATE_ID = `aggregateId`,
  TENANT_ID = `tenantId`,
  OWNER_ID = `ownerId`,
  VERSION = `version`,
  EVENT_ID = `eventId`,
  FIRST_OPERATOR = `firstOperator`,
  OPERATOR = `operator`,
  FIRST_EVENT_TIME = `firstEventTime`,
  EVENT_TIME = `eventTime`,
  DELETED = `deleted`,
  STATE = `state`,
  STATE_AVAILABLE_FILTERS = `state.availableFilters`,
  STATE_AVAILABLE_FILTERS_FILTERS = `state.availableFilters.filters`,
  STATE_AVAILABLE_FILTERS_FILTERS_COMPONENT = `state.availableFilters.filters.component`,
  STATE_AVAILABLE_FILTERS_FILTERS_FIELD = `state.availableFilters.filters.field`,
  STATE_AVAILABLE_FILTERS_FILTERS_FIELD_FORMAT = `state.availableFilters.filters.field.format`,
  STATE_AVAILABLE_FILTERS_FILTERS_FIELD_LABEL = `state.availableFilters.filters.field.label`,
  STATE_AVAILABLE_FILTERS_FILTERS_FIELD_NAME = `state.availableFilters.filters.field.name`,
  STATE_AVAILABLE_FILTERS_FILTERS_FIELD_TYPE = `state.availableFilters.filters.field.type`,
  STATE_AVAILABLE_FILTERS_FILTERS_OPERATOR = `state.availableFilters.filters.operator`,
  STATE_AVAILABLE_FILTERS_FILTERS_OPERATOR_DEFAULT_OPERATOR = `state.availableFilters.filters.operator.defaultOperator`,
  STATE_AVAILABLE_FILTERS_FILTERS_OPERATOR_LOCALE = `state.availableFilters.filters.operator.locale`,
  STATE_AVAILABLE_FILTERS_FILTERS_OPERATOR_SUPPORTED_OPERATORS = `state.availableFilters.filters.operator.supportedOperators`,
  STATE_AVAILABLE_FILTERS_FILTERS_VALUE = `state.availableFilters.filters.value`,
  STATE_AVAILABLE_FILTERS_FILTERS_VALUE_CLASS_NAME = `state.availableFilters.filters.value.className`,
  STATE_AVAILABLE_FILTERS_FILTERS_VALUE_DEFAULT_VALUE = `state.availableFilters.filters.value.defaultValue`,
  STATE_AVAILABLE_FILTERS_FILTERS_VALUE_PLACEHOLDER = `state.availableFilters.filters.value.placeholder`,
  STATE_AVAILABLE_FILTERS_FILTERS_VALUE_STYLE = `state.availableFilters.filters.value.style`,
  STATE_AVAILABLE_FILTERS_LABEL = `state.availableFilters.label`,
  STATE_CHECKABLE = `state.checkable`,
  STATE_COUNT_URL = `state.countUrl`,
  STATE_DATA_URL = `state.dataUrl`,
  STATE_FIELDS = `state.fields`,
  STATE_FIELDS_ATTRIBUTES = `state.fields.attributes`,
  STATE_FIELDS_LABEL = `state.fields.label`,
  STATE_FIELDS_NAME = `state.fields.name`,
  STATE_FIELDS_PRIMARY_KEY = `state.fields.primaryKey`,
  STATE_FIELDS_SORTER = `state.fields.sorter`,
  STATE_FIELDS_SORTER_MULTIPLE = `state.fields.sorter.multiple`,
  STATE_ID = `state.id`,
  STATE_NAME = `state.name`,
}
