packages:
  - packages/*
  - integration-test

catalog:
  '@eslint/js': ^9.38.0
  '@testing-library/react': ^16.0.0
  '@testing-library/jest-dom': ^6.9.1
  '@types/node': ^24.5.2
  '@types/react': '>=19.0.0'
  '@types/react-dom': '>=19.0.0'
  '@vitejs/plugin-react': ^5.1.0
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  '@ant-design/icons': ^5.6.1
  antd: ^5.28.0
  babel-plugin-react-compiler: ^1.0.0
  commander: ^14.0.2
  eslint: ^9.38.0
  eslint-plugin-react-hooks: ^7.0.1
  globals: ^16.5.0
  jsdom: ^27.1.0
  msw: ^2.11.6
  nanoid: ^5.1.6
  prettier: ^3.6.2
  react: '>=19.0.0'
  react-compiler-runtime: ^1.0.0
  react-dom: '>=19.0.0'
  react-use: ^17.6.0
  reflect-metadata: ^0.2.2
  ts-morph: ^27.0.2
  typescript: ^5.9.3
  typescript-eslint: ^8.46.2
  unplugin-dts: 1.0.0-beta.6
  vite: ^7.1.12
  vite-bundle-analyzer: ^1.2.3
  vitest: ^3.2.4
  yaml: ^2.3.1
