packages:
  - packages/*
  - integration-test

catalog:
  '@eslint/js': ^9.37.0
  '@testing-library/react': ^16.0.0
  '@types/node': ^24.5.2
  '@types/react': ^18.0.0
  '@types/react-dom': ^18.0.0
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  commander: ^14.0.0
  eslint: ^9.37.0
  eslint-plugin-react-hooks: ^5.2.0
  globals: ^16.4.0
  jsdom: ^27.0.0
  msw: ^2.11.3
  nanoid: ^5.1.6
  prettier: ^3.6.2
  react: ^18.0.0
  react-dom: ^18.0.0
  react-use: ^17.6.0
  reflect-metadata: ^0.2.2
  ts-morph: ^27.0.0
  typescript: ^5.9.3
  typescript-eslint: ^8.45.0
  unplugin-dts: 1.0.0-beta.6
  vite: ^7.1.9
  vite-bundle-analyzer: ^1.2.3
  vitest: ^3.2.4
  yaml: ^2.3.1
