packages:
  - packages/*
  - integration-test

catalog:
  '@ant-design/icons': ^6.0.0
  '@eslint/js': ^9.39.1
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.0.0
  '@types/node': ^24.10.1
  '@types/react': ">=19.0.0"
  '@types/react-dom': ">=19.0.0"
  '@vitejs/plugin-react': ^5.1.1
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  antd: ^6.0.0
  babel-plugin-react-compiler: ^1.0.0
  commander: ^14.0.2
  dayjs: ^1.11.19
  eslint: ^9.39.1
  eslint-plugin-react-hooks: ^7.0.1
  globals: ^16.5.0
  immer: ^11.0.0
  jsdom: ^27.2.0
  msw: ^2.12.3
  nanoid: ^5.1.6
  prettier: ^3.6.2
  react: ">=19.0.0"
  react-compiler-runtime: ^1.0.0
  react-dom: ">=19.0.0"
  react-use: ^17.6.0
  reflect-metadata: ^0.2.2
  ts-morph: ^27.0.2
  typescript: ^5.9.3
  typescript-eslint: ^8.48.0
  unplugin-dts: 1.0.0-beta.6
  vite: ^7.2.4
  vite-bundle-analyzer: ^1.2.3
  vitest: ^3.2.4
  yaml: ^2.3.1
