packages:
  - 'packages/*'
  - 'integration-test'
catalog:
  "vite": "^7.1.5"
  "vite-bundle-analyzer": "^1.2.3"
  "unplugin-dts": "1.0.0-beta.6"
  "eslint": "^9.35.0"
  "@eslint/js": "^9.35.0"
  "typescript-eslint": "^8.43.0"
  "vitest": "^3.2.4"
  "@vitest/ui": "^3.2.4"
  "@vitest/coverage-v8": "^3.2.4"
  "globals": "^16.4.0"
  "prettier": "^3.6.2"
  "typescript": "^5.9.2"
