packages:
  - packages/*
  - integration-test

catalog:
  '@ant-design/icons': ^6.0.0
  '@eslint/js': ^9.39.2
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.1
  '@types/node': ^24.10.4
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  antd: ^6.2.0
  babel-plugin-react-compiler: ^1.0.0
  commander: ^14.0.2
  dayjs: ^1.11.19
  eslint: ^9.39.2
  eslint-plugin-react-compiler: ^19.1.0-rc.2
  eslint-plugin-react-hooks: ^7.0.1
  globals: ^17.0.0
  immer: ^11.1.3
  jsdom: ^27.4.0
  msw: ^2.12.7
  nanoid: ^5.1.6
  playwright: ^1.57.0
  prettier: ^3.7.4
  react: ^19.2.3
  react-compiler-runtime: ^1.0.0
  react-dom: ^19.2.3
  react-use: ^17.6.0
  reflect-metadata: ^0.2.2
  ts-morph: ^27.0.2
  typescript: ^5.9.3
  typescript-eslint: ^8.53.0
  unplugin-dts: 1.0.0-beta.6
  vite: ^7.3.1
  vite-bundle-analyzer: ^1.3.2
  vitest: ^3.2.4
  yaml: ^2.8.2
