import { HttpMethod, type ResultExtractorCapable } from '@ahoo-wang/fetcher';
import { type ApiMetadata } from './apiDecorator';
import 'reflect-metadata';

export interface PathCapable {
  /**
   * Path for the endpoint (relative to class base path).
   *
   * This path will be appended to the class's base path to form the complete URL.
   * Path parameters can be specified using curly braces, e.g., '/users/{id}'
   */
  path?: string;
}

/**
 * Metadata for HTTP endpoints.
 *
 * Defines the configuration options for individual HTTP endpoints (methods).
 * These settings will override any corresponding class-level settings from ApiMetadata.
 */
export interface EndpointMetadata
  extends ApiMetadata,
    ResultExtractorCapable,
    PathCapable {
  /**
   * HTTP method for the endpoint.
   *
   * Specifies the HTTP verb to be used for this endpoint (GET, POST, PUT, DELETE, etc.)
   */
  method?: HttpMethod;
}

export const ENDPOINT_METADATA_KEY = Symbol('endpoint:metadata');

export type MethodEndpointMetadata = Omit<EndpointMetadata, 'method' | 'path'>;

/**
 * Decorator factory for defining HTTP endpoints.
 *
 * Creates a decorator that can be used to define HTTP endpoints
 * on class methods. It stores metadata about the endpoint that will be used
 * to generate the actual HTTP request.
 *
 * @param method - The HTTP method for this endpoint
 * @param path - The path for this endpoint (relative to class base path)
 * @param metadata - Additional endpoint metadata (headers, timeout, etc.)
 * @returns A method decorator function
 *
 * @example
 * ```typescript
 * @api('/api/v1')
 * class UserService {
 *   @endpoint(HttpMethod.GET, '/users/{id}')
 *   getUser(@path('id') id: string): Promise<Response> {
 *     // Implementation will be generated automatically
 *     throw autoGeneratedError();
 *   }
 * }
 * ```
 */
export function endpoint(
  method?: HttpMethod,
  path?: string,
  metadata: MethodEndpointMetadata = {},
) {
  return function (target: object, propertyKey: string | symbol): void {
    // Store metadata directly on the method
    const endpointMetadata = {
      method: method,
      path,
      ...metadata,
    };
    Reflect.defineMetadata(
      ENDPOINT_METADATA_KEY,
      endpointMetadata,
      target,
      propertyKey,
    );
  };
}

/**
 * Convenience decorator for GET HTTP requests.
 *
 * Creates an endpoint decorator configured for GET requests. GET requests
 * are used to retrieve data from a server without modifying it.
 *
 * @param path - The endpoint path (relative to class base path)
 * @param metadata - Additional endpoint metadata (headers, timeout, etc.)
 * @returns A method decorator function
 *
 * @example
 * ```typescript
 * @api('/api/v1')
 * class UserService {
 *   @get('/users/{id}')
 *   getUser(@path('id') id: string): Promise<User> {
 *     throw autoGeneratedError();
 *   }
 * }
 * ```
 */
export function get(path: string = '', metadata: MethodEndpointMetadata = {}) {
  return endpoint(HttpMethod.GET, path, metadata);
}

/**
 * Convenience decorator for POST HTTP requests.
 *
 * Creates an endpoint decorator configured for POST requests. POST requests
 * are used to create new resources on the server.
 *
 * @param path - The endpoint path (relative to class base path)
 * @param metadata - Additional endpoint metadata (headers, timeout, etc.)
 * @returns A method decorator function
 *
 * @example
 * ```typescript
 * @api('/api/v1')
 * class UserService {
 *   @post('/users')
 *   createUser(@body() user: User): Promise<User> {
 *     throw autoGeneratedError();
 *   }
 * }
 * ```
 */
export function post(path: string = '', metadata: MethodEndpointMetadata = {}) {
  return endpoint(HttpMethod.POST, path, metadata);
}

/**
 * Convenience decorator for PUT HTTP requests.
 *
 * Creates an endpoint decorator configured for PUT requests. PUT requests
 * are used to update existing resources on the server.
 *
 * @param path - The endpoint path (relative to class base path)
 * @param metadata - Additional endpoint metadata (headers, timeout, etc.)
 * @returns A method decorator function
 *
 * @example
 * ```typescript
 * @api('/api/v1')
 * class UserService {
 *   @put('/users/{id}')
 *   updateUser(@path('id') id: string, @body() user: User): Promise<User> {
 *     throw autoGeneratedError();
 *   }
 * }
 * ```
 */
export function put(path: string = '', metadata: MethodEndpointMetadata = {}) {
  return endpoint(HttpMethod.PUT, path, metadata);
}

/**
 * Convenience decorator for DELETE HTTP requests.
 *
 * Creates an endpoint decorator configured for DELETE requests. DELETE requests
 * are used to remove resources from the server.
 *
 * @param path - The endpoint path (relative to class base path)
 * @param metadata - Additional endpoint metadata (headers, timeout, etc.)
 * @returns A method decorator function
 *
 * @example
 * ```typescript
 * @api('/api/v1')
 * class UserService {
 *   @del('/users/{id}')
 *   deleteUser(@path('id') id: string): Promise<void> {
 *     throw autoGeneratedError();
 *   }
 * }
 * ```
 */
export function del(path: string = '', metadata: MethodEndpointMetadata = {}) {
  return endpoint(HttpMethod.DELETE, path, metadata);
}

/**
 * Convenience decorator for PATCH HTTP requests.
 *
 * Creates an endpoint decorator configured for PATCH requests. PATCH requests
 * are used to apply partial updates to existing resources.
 *
 * @param path - The endpoint path (relative to class base path)
 * @param metadata - Additional endpoint metadata (headers, timeout, etc.)
 * @returns A method decorator function
 *
 * @example
 * ```typescript
 * @api('/api/v1')
 * class UserService {
 *   @patch('/users/{id}')
 *   updateUserPartial(@path('id') id: string, @body() updates: Partial<User>): Promise<User> {
 *     throw autoGeneratedError();
 *   }
 * }
 * ```
 */
export function patch(
  path: string = '',
  metadata: MethodEndpointMetadata = {},
) {
  return endpoint(HttpMethod.PATCH, path, metadata);
}

/**
 * Convenience decorator for HEAD HTTP requests.
 *
 * Creates an endpoint decorator configured for HEAD requests. HEAD requests
 * are used to retrieve headers only, without the response body.
 *
 * @param path - The endpoint path (relative to class base path)
 * @param metadata - Additional endpoint metadata (headers, timeout, etc.)
 * @returns A method decorator function
 *
 * @example
 * ```typescript
 * @api('/api/v1')
 * class UserService {
 *   @head('/users/{id}')
 *   checkUserExists(@path('id') id: string): Promise<Response> {
 *     throw autoGeneratedError();
 *   }
 * }
 * ```
 */
export function head(path: string = '', metadata: MethodEndpointMetadata = {}) {
  return endpoint(HttpMethod.HEAD, path, metadata);
}

/**
 * Convenience decorator for OPTIONS HTTP requests.
 *
 * Creates an endpoint decorator configured for OPTIONS requests. OPTIONS requests
 * are used to describe the communication options for the target resource.
 *
 * @param path - The endpoint path (relative to class base path)
 * @param metadata - Additional endpoint metadata (headers, timeout, etc.)
 * @returns A method decorator function
 *
 * @example
 * ```typescript
 * @api('/api/v1')
 * class UserService {
 *   @options('/users')
 *   getUserOptions(): Promise<Response> {
 *     throw autoGeneratedError();
 *   }
 * }
 * ```
 */
export function options(
  path: string = '',
  metadata: MethodEndpointMetadata = {},
) {
  return endpoint(HttpMethod.OPTIONS, path, metadata);
}
