/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Fails fast when a decorator is applied as a TC39 standard decorator.
 *
 * These decorators are TypeScript `experimentalDecorators`: they receive the
 * prototype and a property key. Compiled as standard decorators (TypeScript 5
 * without `experimentalDecorators`) they receive a context object instead,
 * which would otherwise be stored as a property name and surface only as an
 * `AutoGenerated` error on the first call.
 *
 * @internal
 */
export function assertLegacyDecorator(context: unknown, decorator: string) {
  if (typeof context === 'object' && context !== null && 'kind' in context) {
    throw new TypeError(
      `${decorator} is a TypeScript experimental decorator: enable ` +
        '"experimentalDecorators" in tsconfig.json (standard decorators are not supported).',
    );
  }
}
