/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Fetcher, type FetchExchange } from '@ahoo-wang/fetcher';
import {
  api,
  attribute,
  autoGeneratedError,
  get,
  header,
  path,
  query,
} from '../src';

// What reached fetch, and the attributes interceptors saw.
let sent: { url: string; headers: Headers } | undefined;
let seenAttributes: Map<string, any> | undefined;

const fetcher = new Fetcher({ baseURL: 'https://binding.test' });
fetcher.interceptors.request.use({
  name: 'RecordAttributes',
  order: 0,
  intercept(exchange: FetchExchange) {
    seenAttributes = exchange.attributes;
  },
});

beforeEach(() => {
  sent = undefined;
  seenAttributes = undefined;
  vi.stubGlobal('fetch', async (url: string, init: RequestInit) => {
    sent = { url, headers: new Headers(init.headers as HeadersInit) };
    return new Response('{}');
  });
});

class Profile {
  constructor(readonly id: string) {}
}

@api('/items', { fetcher })
class ItemService {
  @get('/{id}')
  byId(@path('id') id: string, @query('ids') ids?: number[]): Promise<void> {
    throw autoGeneratedError(id, ids);
  }

  @get('/')
  search(
    @query() filter: { status?: string; page?: number },
    @query('since') since?: Date,
  ): Promise<void> {
    throw autoGeneratedError(filter, since);
  }

  @get('/')
  withHeaders(
    @header('Accept-Language') languages: string[],
    @header() extra: Record<string, string | undefined>,
  ): Promise<void> {
    throw autoGeneratedError(languages, extra);
  }

  @get('/')
  withAttributes(
    @attribute('user') user: { id: string },
    @attribute() attributes?: Record<string, unknown>,
    @attribute() profile?: Profile,
  ): Promise<void> {
    throw autoGeneratedError(user, attributes, profile);
  }
}

const service = new ItemService();

describe('argument binding', () => {
  it('binds an array to its name, sent as repeated query keys', async () => {
    await service.byId('a', [1, 2]);
    expect(sent?.url).toBe('https://binding.test/items/a?ids=1&ids=2');
  });

  it('spreads a plain object and sends a Date as ISO 8601', async () => {
    await service.search(
      { status: 'open', page: undefined },
      new Date(Date.UTC(2026, 0, 2)),
    );
    expect(sent?.url).toBe(
      'https://binding.test/items/?status=open&since=2026-01-02T00%3A00%3A00.000Z',
    );
  });

  it('sends an array header as a list and lets an object entry remove a header', async () => {
    await service.withHeaders(['zh', 'en'], { 'X-A': 'a', 'X-B': undefined });
    expect(sent?.headers.get('accept-language')).toBe('zh, en');
    expect(sent?.headers.get('x-a')).toBe('a');
    expect(sent?.headers.has('x-b')).toBe(false);
  });

  it('stores an explicitly named attribute under its name, merges an unnamed record', async () => {
    const profile = new Profile('p-1');
    await service.withAttributes({ id: 'u-1' }, { tenant: 't-1' }, profile);
    expect(seenAttributes?.get('user')).toEqual({ id: 'u-1' });
    expect(seenAttributes?.get('tenant')).toBe('t-1');
    // Not a plain object: stored under the inferred name, not spread.
    expect(seenAttributes?.get('profile')).toBe(profile);
    expect(seenAttributes?.has('id')).toBe(false);
  });
});

describe('executor binding', () => {
  it('keeps a subclass override of an endpoint that has no decorator of its own', async () => {
    @api('/child', { fetcher })
    class Child extends ItemService {
      override byId(): Promise<void> {
        return Promise.resolve();
      }
    }
    await new Child().byId();
    expect(sent).toBeUndefined();
  });

  it('rebinds an inherited endpoint to the subclass base path', async () => {
    @api('/child', { fetcher })
    class Child extends ItemService {}
    await new Child().byId('a');
    expect(sent?.url).toBe('https://binding.test/child/a');
  });

  it('explains a call without the service instance', async () => {
    const { byId } = service;
    await expect(byId('a')).rejects.toThrow(
      'ItemService.byId was called without its instance',
    );
  });

  it('adds no field to the service instance', async () => {
    const instance = new ItemService();
    await instance.byId('a');
    expect(Object.keys(instance)).toEqual([]);
  });
});

describe('standard (TC39) decorators', () => {
  const context = { kind: 'method', name: 'm' };

  it('are rejected by method decorators with a pointer to experimentalDecorators', () => {
    expect(() => (get('/x') as any)(() => {}, context)).toThrow(
      /experimentalDecorators/,
    );
  });

  it('are rejected by @api', () => {
    expect(() =>
      (api('/x') as any)(class {}, { kind: 'class', name: 'X' }),
    ).toThrow(/experimentalDecorators/);
  });
});
