import { describe, it, expect } from 'vitest';
import { autoGeneratedError, AutoGenerated } from '../src';

describe('generated', () => {
  it('should create auto generated error', () => {
    const error = autoGeneratedError();
    expect(error).toBeInstanceOf(Error);
    expect(error).toBeInstanceOf(AutoGenerated);
    expect(error.message).toBe(
      'Implementation will be generated automatically.',
    );
    expect(error.name).toBe('AutoGenerated');
  });
});
