/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ContentTypeValues, Fetcher } from '@ahoo-wang/fetcher';
import { CommandResult, CommandResultEventStream } from './commandResult';
import { api, autoGeneratedError, endpoint, request, ResultExtractors } from '@ahoo-wang/fetcher-decorator';
import { CommandHttpRequest } from './commandHttpRequest';

@api()
export class CommandHttpClient {
  constructor(public readonly fetcher: Fetcher) {
  }

  @endpoint()
  send(@request() commandHttpRequest: CommandHttpRequest): Promise<CommandResult> {
    throw autoGeneratedError(commandHttpRequest);
  }

  @endpoint(undefined, undefined, {
    headers: {
      Accept: ContentTypeValues.TEXT_EVENT_STREAM,
    },
    resultExtractor: ResultExtractors.JsonEventStream,
  })
  async sendAndWait(@request() commandHttpRequest: CommandHttpRequest): Promise<CommandResultEventStream> {
    throw autoGeneratedError(commandHttpRequest);
  }
}